export const pictures = [
	{ id: 1, imgUrl: "/gallery/1.jpg" },
	{ id: 2, imgUrl: "/gallery/2.webp" },
	{ id: 3, imgUrl: "/gallery/3.webp" },
	{ id: 4, imgUrl: "/gallery/4.jpg" },
	{ id: 5, imgUrl: "/gallery/5.jpg" },
	{ id: 6, imgUrl: "/gallery/6.webp" },
	{ id: 7, imgUrl: "/gallery/7.webp" },
	{ id: 8, imgUrl: "/gallery/8.webp" },
	{ id: 9, imgUrl: "/gallery/9.webp" },
	{ id: 10, imgUrl: "/gallery/10.webp" },
	{ id: 11, imgUrl: "/gallery/11.webp" },
	// { id: 12, imgUrl: "/gallery/12.webp" },
	// { id: 13, imgUrl: "/gallery/13.webp" },
	// { id: 14, imgUrl: "/gallery/14.webp" },
	// { id: 15, imgUrl: "/gallery/15.webp" },
	// { id: 16, imgUrl: "/gallery/16.webp" },
	// { id: 17, imgUrl: "/gallery/17.webp" },
	// { id: 18, imgUrl: "/gallery/18.webp" },
	// { id: 19, imgUrl: "/gallery/19.webp" },
];

export const livings = [
	{
		id: 1,
		category: "Livings",
		name: "Moderno",
		title: "Juego de muebles para 10 personas ",
		description: "Juego de muebles para 10 personas",
		price: "$ 10.000",
		url: "/productos/LivingModerno/1.webp",
		items: [
			"1 sillón de ecocuero blanco, doble y con respaldo",
			"1 puff doble de ecocuero blanco",
			"6 puffs de ecocuero blanco",
			"1 mesa de madera blanca",
			"Almohadón decorativo",
			"Plato de sitio decorativo",
		],
		pictures: [
			{ id: 1, imgUrl: "/productos/LivingModerno/1.webp" },
			{ id: 2, imgUrl: "/productos/LivingModerno/2.webp" },
			{ id: 3, imgUrl: "/productos/LivingModerno/3.webp" },
			{ id: 4, imgUrl: "/productos/LivingModerno/4.webp" },
			{ id: 5, imgUrl: "/productos/LivingModerno/5.webp" },
			{ id: 6, imgUrl: "/productos/LivingModerno/6.webp" },
		],
	},
	{
		id: 2,
		category: "Livings",
		name: "Industrial",
		title: "Juego de muebles para 10 personas ",
		description: "Juego de muebles para 10 personas",
		price: "$ 9.000",
		url: "/productos/LivingIndustrial/1.webp",
		items: [
			"1 sillón de tres cuerpos, de hierro negro y madera color roble",
			"1 banqueta de 3 cuerpos, de hierro negro y madera color roble",
			"4 cubos, de hierro negro y madera color roble",
			"1 mesa, de hierro negro y madera color roble",
			"Almohadón decorativo",
			"Plato de sitio decorativo",
		],
		pictures: [
			{ id: 1, imgUrl: "/productos/LivingIndustrial/1.webp" },
			{ id: 2, imgUrl: "/productos/LivingIndustrial/2.webp" },
			{ id: 3, imgUrl: "/productos/LivingIndustrial/3.webp" },
			{ id: 4, imgUrl: "/productos/LivingIndustrial/4.webp" },
		],
	},
	{
		id: 3,
		category: "Livings",
		name: "Rústico",
		title: "Juego de muebles para 10 personas ",
		description: "Juego de muebles para 10 personas",
		price: "$ 10.000",
		url: "/productos/LivingRustico/1.webp",
		items: [
			"1 mesa de madera, en color roble o blanca",
			"Sillón, puffs, sillas y cubos (pueden ser distintas combinaciones)",
			"Almohadón decorativo",
			"Plato de sitio decorativo",
		],
		pictures: [
			{ id: 1, imgUrl: "/productos/LivingRustico/1.webp" },
			{ id: 2, imgUrl: "/productos/LivingRustico/2.webp" },
			{ id: 3, imgUrl: "/productos/LivingRustico/3.webp" },
			{ id: 4, imgUrl: "/productos/LivingRustico/4.webp" },
			{ id: 5, imgUrl: "/productos/LivingRustico/5.webp" },
			{ id: 6, imgUrl: "/productos/LivingRustico/6.webp" },
		],
	},
	{
		id: 4,
		category: "Livings",
		name: "Infantil",
		title: "Mini living para 10 niños",
		description: "Mini living para 10 niños",
		price: "$ 5.000",
		url: "/productos/LivingInfantil/1.webp",
		items: [
			"18 puffs de ecocuero en varios colores",
			"1 tablón de madera con caballetes en hierro y mantel de material tropical mecánico en color blanco ",
		],
		pictures: [
			{ id: 1, imgUrl: "/productos/LivingInfantil/1.webp" },
			{ id: 2, imgUrl: "/productos/LivingInfantil/2.webp" },
			{ id: 3, imgUrl: "/productos/LivingInfantil/3.webp" },
			{ id: 4, imgUrl: "/productos/LivingInfantil/4.webp" },
			{ id: 5, imgUrl: "/productos/LivingInfantil/5.webp" },
			{ id: 6, imgUrl: "/productos/LivingInfantil/6.webp" },
		],
	},
	{
		id: 5,
		category: "Livings",
		name: "Black & White",
		title: "Juego de muebles para 10 personas ",
		description: "Juego de living para 10 personas",
		price: "$ 12.500",
		url: "/productos/LivingBlackWhite/1.webp",
		items: [
			"1 sillón de ecocuero blanco, doble y con respaldo",
			"6 puffs individuales de ecocuero blancos y negros",
			"1 puff doble de ecocuero blanco",
			"1 mesa de madera blanca",
			"almohadón decorativo",
			"plato de sitio decorativo",
		],
		pictures: [
			{ id: 1, imgUrl: "/productos/LivingBlackWhite/1.webp" },
			{ id: 2, imgUrl: "/productos/LivingBlackWhite/2.webp" },
			{ id: 3, imgUrl: "/productos/LivingBlackWhite/3.webp" },
			{ id: 4, imgUrl: "/productos/LivingBlackWhite/4.webp" },
			{ id: 5, imgUrl: "/productos/LivingBlackWhite/5.webp" },
			{ id: 6, imgUrl: "/productos/LivingBlackWhite/6.webp" },
		],
	},
];

export const otrosProductos = [
	{
		id: 1,
		category: "Productos",
		name: "Barra para tragos",
		title: "Barra móvil reforzada",
		description:
			"Barra alta, móvil, reforzada, de madera  varillada y en color roble.",
		price: "$ 8.000",
		url: "/productos/BarraTragos/1.webp",
		pictures: [
			{ id: 1, imgUrl: "/productos/BarraTragos/1.webp" },
			{ id: 2, imgUrl: "/productos/BarraTragos/2.webp" },
			{ id: 3, imgUrl: "/productos/BarraTragos/3.webp" },
		],
	},

	{
		id: 2,
		category: "Productos",
		name: "Barritas altas y banquetas",
		title: "Barra alta con 4 banquetas",
		description: "Juego para 4 personas.",
		price: "$ 7.000",
		url: "/productos/BarraAlta/1.webp",
		items: [
			"Mesa alta de hierro negro y madera color roble",
			"4 banquetas altas de hierro negro y madera color roble",
		],
		pictures: [{ id: 1, imgUrl: "/productos/BarraAlta/1.webp" }],
	},
	{
		id: 3,
		category: "Productos",
		name: "Sillas Country",
		title: "Sillas tipo country plegables",
		description:
			"Sillas estilo country, de madera, en color blancas y plegables.",
		price: "$ 300",
		url: "/productos/SillasCountry/1.webp",
		pictures: [
			{ id: 1, imgUrl: "/productos/SillasCountry/1.webp" },
			{ id: 2, imgUrl: "/productos/SillasCountry/2.webp" },
			{ id: 3, imgUrl: "/productos/SillasCountry/3.webp" },
			{ id: 4, imgUrl: "/productos/SillasCountry/4.webp" },
			{ id: 5, imgUrl: "/productos/SillasCountry/5.webp" },
		],
	},
	{
		id: 4,
		category: "Productos",
		name: "Tablones y manteles",
		title: "Tablones y manteles blancos o negros",
		description: "Tablones de madera con caballetes de hierro. (Costo: $2000)",
		price: "$ 300",
		url: "/productos/MesasManteles/1.webp",
		pictures: [
			{ id: 1, imgUrl: "/productos/MesasManteles/1.webp" },
			{ id: 2, imgUrl: "/productos/MesasManteles/2.webp" },
			{ id: 3, imgUrl: "/productos/MesasManteles/3.webp" },
			{ id: 4, imgUrl: "/productos/MesasManteles/4.webp" },
			{ id: 5, imgUrl: "/productos/MesasManteles/5.webp" },
		],
	},
	{
		id: 5,
		category: "Productos",
		name: "Jenga gigante",
		title: "Juego de madera",
		description: "Juego de madera",
		price: "$ 10.000",
		url: "/productos/Jenga/1.webp",
		pictures: [
			{ id: 1, imgUrl: "/productos/Jenga/1.webp" },
			{ id: 2, imgUrl: "/productos/Jenga/2.webp" },
			{ id: 3, imgUrl: "/productos/Jenga/3.webp" },
		],
	},
	{
		id: 6,
		category: "Productos",
		name: "Mesa civil",
		title: "Mesa de madera",
		description: "Mesa de madera en color roble con patas de hierro negro.",
		price: "$ 5.000",
		url: "/productos/MesaCivil/1.webp",
		pictures: [{ id: 1, imgUrl: "/productos/MesaCivil/1.webp" }],
	},
];
